# Generated by Django 3.2.7 on 2021-09-27 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ManyToManyField(related_name='building', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateRestroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanitation_score', models.IntegerField()),
                ('safe_score', models.IntegerField()),
                ('suggest_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestroomVisitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=30)),
                ('made_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('link_recieved_time', models.DateTimeField(blank=True, null=True)),
                ('qr_open_time', models.DateTimeField(blank=True, null=True)),
                ('qr_scan_time', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('qr', models.CharField(max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('p_restroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.privaterestroom')),
            ],
        ),
        migrations.CreateModel(
            name='Restroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=32)),
                ('location_information', models.CharField(max_length=30, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.building')),
                ('reviews', models.ManyToManyField(blank=True, to='server.Review')),
            ],
        ),
        migrations.AddField(
            model_name='privaterestroom',
            name='restroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.restroom'),
        ),
    ]
